### ISSUE TITLE
Frequency interval not constant

### ISSUE THREAD

**Issue by sebprince** [dunewires/ElectricalMethod#14]
While doing a long frequency sweep, I noticed on the oscilloscope that the frequency values were changing at an accelerating rate, indicating that the frequency interval increases either with larger frequencies or with duration or the test.

The frequency interval should stay constant.

**Comment by jbattat** [comment]
Interesting -- the *reported* frequency step (in the frequency header) is essentially constant (though smaller than the requested step by a factor of 2) -- see attached histogram showing the frequency step for a run that Sebastien sent me (20200813T000904).  But perhaps the actual frequency step differs from the reported frequency step (computed by differencing reported frequencies).  But we do know that the actual frequencies (measured on oscilloscope) of the start and end of scan are correct.  So this issue is a puzzle to me...
![20200813T000904_freqdifferences_noOutlier](https://user-images.githubusercontent.com/8468957/90799080-beced880-e2e0-11ea-9481-125c63605a30.png)

**Comment by sebprince** [comment]
I only noticed that in a long sweep, from a few tens of hertz to a few kilohertz. It could be the effect is negligible when scanning only a 10 Hz range. I'll record data so we that can check that visual observation.

**Comment by sebprince** [comment]
I did a scan with v4_0 from 10 Hz to 10 kHz and the frequency interval seemed constant both in time taking per frequency and step size. It wasn't accelerating in size as previously observed. Closing this issue.
