### ISSUE TITLE
Avoid splitting a UDP payload

### ISSUE THREAD

**Issue by jbattat** [dunewires/ElectricalMethod#5]
At present, a UDP payload that is larger than 128 x 32-bit words are automatically split across multiple UDP transmissions.  We don't want this.

Some potentially useful information:

* looks like packet length can be much larger (64k bits, or ~2k 32-bit words): 
https://serverfault.com/questions/246508/how-is-the-mtu-is-65535-in-udp-but-ethernet-does-not-allow-frame-size-more-than
* could also implement "jumbo" packets

**Comment by sebprince** [comment]
This might have been fixed in v4_0, but I'm not sure how to test if this has been fixed. I could possibly manually use `udpRecDwa.py` to investigate UDP packets but I'm not sure if this module still works.

@jbattat do you know what would be the best way to test for this, or maybe you can comment yourself directly about the status of this issue?

**Comment by sebprince** [comment]
I confirm that this issue is still relevant in v4_0.

I tested by running with 128 samples per frequency, corresponding to slightly more than 64 32-bit words and the DAQ worked fine. There's no separation of a single frequency and data header, which should be contained in a single UDP packet, in the raw UDP data of `udpstream.txt`.

I tested by running with 256 samples per frequency, corresponding to slightly more than 128 32-bit words. The raw UDP data (attached: [udpstream.txt](https://github.com/dunewires/ElectricalMethod/files/5999670/udpstream.txt)) shows the data frame being split into two UDP packets.
Interestingly, the total number of samples is 384, larger than 256. This could be a consequence of the separation of the data.
Additionally, the DAQ crashed with this error after the first data frame:
```
Traceback (most recent call last):
  File "dwaDaq.py", line 171, in run
    result = self.fn(*self.args, **self.kwargs)
  File "dwaDaq.py", line 900, in startUdpReceiver
    while not dataStrings[0].startswith("AAAA"):
IndexError: list index out of range
```
It is possible this is because the DAQ wasn't expecting a new UDP packet within a data frame, thus being a downstream issue of the current one.

**Comment by jbattat** [comment]
@sebprince Thanks for confirming this issue. You are correct that the python daq crash is secondary, and is a direct result of receiving a UDP packet whose contents are "out of spec" .

We should find a good way to avoid data from the FPGA being split across multiple UDP packets. Worst case, we could have an intermediate step on the daq side that "stitches together" udp packets where necessary, prior to parsing those packets. But that approach is less preferable than avoiding the splitting of packets in the first place.

**Comment by sebprince** [comment]
I don't think stitching packets would work since in the test the union of the two data packets had have more samples than expected. I'm not sure what causes this. It might be that `udpstream.txt` is badly written as the DAQ does not expect such a packet split, but since that file is supposed to be a mere packet dump I'm guessing the issue lies in the firmware. So this would need to be fixed at that level.

**Comment by jbattat** [comment]
FWIW, the python daq dumps each bit from the UDP payload that it receives to udpstream.txt, without any processing. So it’s safe to assume that the UDP payload(s) in udpstream.txt match what the python daq received.

**Comment by sebprince** [comment]
This won't be implemented. Instead a validation check on the configuration parameter, see #83, limits the number of data samples. The upper boundary on the product of cyclesPerFreq and adcSamplesPerCyclehas has been set to <=128. Closing.
